### ISSUE TITLE
Question about edge filtering operation

### ISSUE THREAD

**Issue by Shi-Qi-Li** [sunghoon031/HARA#1]
Hi @sunghoon031,
Thanks for sharing the code! 
I have a question about the edge filtering operation mentioned in the paper, I'm wondering if there's a possibility that this operation breaks the connectivity of the pose graph.
Thanks!

**Comment by sunghoon031** [comment]
Hi. Thanks for your interest!
This won't happen, because the initialization gives us the spanning tree. 
Even if all other edges are identified as outliers, all views will be connected by at least one edge for this reason.
Hope this answers your question!

**Comment by Shi-Qi-Li** [comment]
> Hi. Thanks for your interest! This won't happen, because the initialization gives us the spanning tree. Even if all other edges are identified as outliers, all views will be connected by at least one edge for this reason. Hope this answers your question!

Thanks for your reply, that solved my problem.
